baseURL = "https://cuong.buiquang.com/"
languageCode = "en-us"
title = "BQC"
theme = "hf"
paginate = 5

[params]
  contentTypeName = "blog"
  defaultThem = "light"
  toc = false

[languages]
  [languages.en]
    title = "BQC"
    subtitle = "Software Vulnerability Gossip"
    keyword = ""
    copyright = "© 2021 Cuong Bui Quang"
    menuMore = "Show more"
    writtenBy = "Written By"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer Posts"
    olderPosts = "Older Posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"

    [languages.en.params.logo]
      logoText = "BQC"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
    [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"

