baseURL = "https://cuong.buiquang.com/"
languageCode = "en-us"
title = "BUI Quang Cuong"
theme = "hf"
paginate = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  contentTypeName = "blog"
  defaultTheme = "light"
  toc = false

[languages]
  [languages.en]
    title = "BUI Quang Cuong"
    subtitle = "Software Vulnerability Gossip"
    keyword = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written By"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer Posts"
    olderPosts = "Older Posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"

    [languages.en.params.logo]
      logoText = "[root@bqc]#"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "todo"
        name = "TODO"
        url = "/todo"
    [[languages.en.menu.main]]
        identifier = "blog"
        name = "BLOG"
        url = "/blog"

